### ISSUE TITLE
Xenon daemon runnin

### ISSUE THREAD

**Issue by looneyandy** [aspenluxxxy/xenon-docs#1]
## Setup (please complete the following information):
 - **iOS Version**:  14.2
 - **Jailbreak used**: unc0ver
 - **Computer OS**:windows 8.1 

## Additional context
Have the .exe running on my windows 8.1, go to pair and get the qr on screen, go on phone to xenon and press pair, scans the pic and then when I try to mount I get “ are you sure the xenon daemon is running” - is this on the pic of the phone?

**Comment by aspenluxxxy** [comment]
Do you have discord? I have a possible new version waiting for be uploaded that might fix this.

**Comment by jesseuwu** [comment]
Getting the same issue, pretty much anything I try to press gets "Failed to communicate with the Xenon daemon".

Is there a Discord server for this?

**Comment by looneyandy** [comment]
Yeh I got discord , you have the link?

**Comment by JoeyEamigh** [comment]
I have this issue as well - iPhone 12 Pro

**Comment by aspenluxxxy** [comment]
I've set up a basic discord server: https://discord.gg/GYDFhMfDYF

**Comment by aspenluxxxy** [comment]
I've also created a pinned issue detailing the fix to the issue: https://github.com/aspenluxxxy/xenon-docs/issues/2
