### ISSUE TITLE
KNOWN ISSUE - Xenon daemon not running

### ISSUE THREAD

**Issue by aspenluxxxy** [aspenluxxxy/xenon-docs#2]
In Xenon 1.0.0, you may get "Xenon daemon not running".

This will be fixed in the next release. For now, **manually create the directory** `/var/mobile/Library/me.aspenuwu.xenon`. You can do this from SSH or Filza.

if using SSH, run these commands:
```
mkdir /var/mobile/Library/me.aspenuwu.xenon
chown mobile /var/mobile/Library/me.aspenuwu.xenon
```

**Comment by looneyandy** [comment]
Ok, now I can connect, and creat a mount point, but where do I actually see the connection on my computer?

**Comment by aspenluxxxy** [comment]
The Xenon client should make it visible after you pair and it displays the "connected" notification on your PC.

If not, see https://github.com/aspenluxxxy/xenon-docs#wait-how-do-i-access-my-files

**Comment by looneyandy** [comment]
I see it’s connected on my ox in the top corner, but nothing in windows explorer etc, what am I doing wrong?

**Comment by aspenluxxxy** [comment]
you might need to manually map the URL `http://localhost:4200`

see this tutorial: https://www.maketecheasier.com/map-webdav-drive-windows10/

**Comment by looneyandy** [comment]
Great, got it working now

**Comment by aspenluxxxy** [comment]
1.0.1 was released earlier, fixes this issue.
