### ISSUE TITLE
Major Connection Issues Using Windows 10

### ISSUE THREAD

**Issue by graphixmain** [aspenluxxxy/xenon-docs#3]
## Describe the bug
Windows isn't finding the Dameon. Having a hard time connecting to my IP. 
19:21:37 [WARN] Failed to connect to "IP ADDRESS"; trying again in 15 seconds: Os { code: 10060, kind: TimedOut, message: "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." } 

## Expected behavior
I looked at the troubleshoots and still couldn't fix the error. I also cannot find this in my Windows defender to activate it. 

## Screenshots
If applicable, add screenshots to help explain your problem
![image](https://user-images.githubusercontent.com/79938022/109703992-f5689400-7b4a-11eb-95c1-b76a7ae57be3.png)

.

## Setup (please complete the following information):
14.3
UnCover
Windows 10

**Comment by aspenluxxxy** [comment]
Did you apply the fix at https://github.com/aspenluxxxy/xenon-docs/issues/2?

**Comment by graphixmain** [comment]
Having trouble connecting to "http://localhost:4200"  its not working.

**Comment by graphixmain** [comment]
it's asking for a password and username > Hits enter> cant connect 

![image](https://user-images.githubusercontent.com/79938022/109707938-9f4a1f80-7b4f-11eb-8239-1967d12d69f8.png)
![image](https://user-images.githubusercontent.com/79938022/109707992-acffa500-7b4f-11eb-8267-501d67679712.png)

**Comment by graphixmain** [comment]
I turned n Network Discovery and also added the folder in Filza. That seems to be working on that end and I can mount but my PC is the problem right now with it not showing up. Ill try to restart.

**Comment by aspenluxxxy** [comment]
> it's asking for a password and username > Hits enter> cant connect

@graphixmain weird. You're getting a notification when the client connects, right?

**Comment by graphixmain** [comment]
No Notification at all. I downloaded the Client and Just started it then nothing happens

**Comment by graphixmain** [comment]
I also cant open up the Config file either.  I dont have a program that can open it.

**Comment by aspenluxxxy** [comment]
You can open the config folder, then right click on `config.toml` and open it up with notepad or whatever.

**Comment by graphixmain** [comment]
Alright. Let me see if this works because my phone looks good. ![image](https://user-images.githubusercontent.com/79938022/109711741-0c5fb400-7b54-11eb-80db-1a31f6f1cf1c.jpeg)

**Comment by graphixmain** [comment]
It's working now. Thank you!!!

**Comment by aspenluxxxy** [comment]
glad to have helped :)
