### ISSUE TITLE
Daemon Issue

### ISSUE THREAD

**Issue by R0GUEEE** [aspenluxxxy/xenon-docs#5]
While attempting to pair device to PC, the QR is scanned, followed by haptic feedback, but no notification. While trying to run any of the options in the preference client, a popup details "Failed to communicate with the Xenon daemon. Are you sure that the Xenon daemon is currently running?". I've uninstalled/reinstalled, rebooted the device, allowed the xenon PC client through the firewall, manually created the me.aspenuwu.xenon directory in both filza, and via ssh. Both devices actively connected to the same network. Also ensured windows firewall is disabled entirely, and updated to latest 1.0.1 release. Still no luck.

**Comment by aspenluxxxy** [comment]
1. is there a `crash.log` in `/var/mobile/Library/me.aspenuwu.xenon`?
2. if so, upload it
3. if not, try to see if you can copy the log from the preferences, this shouldn't rely on the daemon at all.

**Comment by leonguyen52** [comment]
I got same problem, tried same ways with @R0GUEEE : uninstalled/reinstalled, rebooted the device, allowed the xenon PC client through the firewall. It just didn't work...

No crash.log in /var/mobile/Library/me.aspenuwu.xenon, only daemon.log but it's empty

Xenon logs on my PC: https://paste.ee/p/TY0Cu
10:16:02 [INFO] started webserver
10:16:03 [INFO] latest version is 1.0.1, our version is 1.0.1

**Comment by aspenluxxxy** [comment]
If you created the `/var/mobile/Library/me.aspenuwu.xenon` directory manually, try deleting it then reinstalling.

**Comment by leonguyen52** [comment]
@aspenluxxxy No. I didn't create it manually. It's already there when I tried to follow your guide above.

**Comment by aspenluxxxy** [comment]
did you try deleting then reinstalling

**Comment by leonguyen52** [comment]
Just tried to delete and reinstall. Still got same error with daemon

**Comment by aspenluxxxy** [comment]
Do you use Discord? I can try to send some debug builds if you'd like, https://discord.gg/GYDFhMfDYF

**Comment by aspenluxxxy** [comment]
Issue has been resolved.

---

IF YOU ARE GETTING "Xenon Daemon Not Running" ON XENON VERSION 1.0.1, YOU NEED TO DM ME THESE THINGS, OVER TWITTER OR DISCORD:
 - chariz proof of purchase
 - your UDID and iPhone model

My twitter is [aspenluxxxy](https://twitter.com/aspenluxxxy), and [there is a Discord server invite.](https://discord.gg/GYDFhMfDYF)
