### ISSUE TITLE
Working on OSX but not Windows

### ISSUE THREAD

**Issue by McMdesigns** [aspenluxxxy/xenon-docs#6]
## Describe the bug
Everything is working perfectly on OSX but on my PC the device does not show up in File Explorer despite pairing being successful. I get the notification that says “Xenon connected” with my iPhone name and IP but it does not show up in file explorer. If I go to http://localhost:4200 nothing loads and I get a 405 error. I tried restarting the PC but it’s still not showing. 

## To Reproduce
1. Pair device with Windows Xenon server
2. Pairing successful
3. Device doesn’t show up in file explorer

## Expected behavior
Device shows up in file explorer

## Setup (please complete the following information):
 - **iOS Version**: 14.1
 - **Jailbreak used**: Unc0ver
 - **Computer OS**: Windows 10 Pro 19043.844

**Comment by aspenluxxxy** [comment]
I believe I've fixed this bug in version 1.0.2 of the client.

For now, follow https://github.com/aspenluxxxy/xenon-docs#wait-how-do-i-access-my-files

**Comment by McMdesigns** [comment]
Ohhh I see now, that worked perfectly, thanks! Such an awesome tweak.
